---
- hosts: demoservers
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World