---
- hosts: demoservers
  vars:
      user: ec2-user
  tasks:
    - name: Print message
      debug:
        msg: "Hello Ansible World at IPv4 address: {{ ansible_default_ipv4.address }}"

    - name: Creates test files
      file:
        path: /tmp/ansible-{{ item }}
        state: touch
      loop:
        - sammy
        - erika
        - brian

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started    
